[package]
name = "mdlayout"
version = "0.1.0"
authors = ["Claus Wilke <wilke@austin.utexas.edu>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
pulldown-cmark = { version = "0.7", default-features = false, features = ["simd"] }
